AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for a Node.js Lambda that uses DynamoDB.
Parameters:
  DynamoTableName:
    Type: String
    Default: Products
    Description: DynamoDB table name for the Lambda to use
  LocalDynamoEndpoint:
    Type: String
    Default: ""
    Description: Local DynamoDB endpoint for sam local testing
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: entityType
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

      GlobalSecondaryIndexes:
        - IndexName: GSI1-EntityType
          KeySchema:
            - AttributeName: entityType
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  DynamoDBGraphLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dynamodb-graph
      Description: Shared DynamoDB graph utility layer for Lambda functions
      ContentUri: ../gravelmon-dynamodb-graph/nodejs/dist/lambda-layer.zip
      CompatibleRuntimes:
        - nodejs18.x

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dist/test-handler.handler
      Runtime: nodejs18.x
      Layers:
        - !Ref DynamoDBGraphLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /test
            Method: get
      Timeout: 10

  DynamoRelationalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dist/handler.handler
      Runtime: nodejs18.x
      Layers:
        - !Ref DynamoDBGraphLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTableName
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoTableName
          DYNAMODB_ENDPOINT: !Ref LocalDynamoEndpoint
          AWS_REGION: !Ref AWS::Region
      Events:
        Api:
          Type: Api
          Properties:
            Path: /items
            Method: any
Outputs:
  ApiUrl:
    Description: Lambda API endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items"
  TableName:
    Description: The DynamoDB table name
    Value: !Ref DynamoTableName
